name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

version: "3.0"

services:
  bookApi:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080

jobs: 
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag smartdubaibookapi:$(date +%s)
