name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

version: "3.0"

services:
  bookApi:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
